### ISSUE TITLE
Detect and handle empty input file

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-lf-python-data#21]
The gate-lf-tests:train-pytorch-singlefeature1 and train-keras-singlefeature1 tests produce the following error:
```
Traceback (most recent call last):
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-keras-singlefeat1/FileJsonKeras/train.py", line 24, in <module>
    ds = Dataset(metafile, targets_need_padding=False)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-keras-singlefeat1/FileJsonKeras/gate-lf-python-data/gatelfdata/dataset.py", line 120, in __init__
    self.features = Features(self.meta, self.vocabs)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-keras-singlefeat1/FileJsonKeras/gate-lf-python-data/gatelfdata/features.py", line 75, in __init__
    self.vocabs.setup_vocab(attrinfo, stats[f["name"]])
KeyError: '┆string╬A'
```

**Comment by johann-petrak** [comment]
This looks like a result of the data file to be empty and the metadata file reflecting 0 instances.
Need to investigate how that happens.

**Comment by johann-petrak** [comment]
OK, this happened because we copied from the wrong set. Changing this into an issue about better detecting and handling an empty input file.

**Comment by johann-petrak** [comment]
Empty input file can get created if there are now instance annotations in the whole corpus.
This should get handled more gracefully but should also get detected by the LearningFramework.

**Comment by johann-petrak** [comment]
This should now get avoided in the LearningFramework already
