### ISSUE TITLE
Error when training for sequence chunking

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-lf-python-data#22]
This happens with the gate-lf-tests:seq-wikiner set and train-pytorch-singlefeature1.

We get the following error:
```
Traceback (most recent call last):
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-pytorch-json/train.py", line 174, in <module>
    main(sys.argv)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-pytorch-json/train.py", line 145, in main
    wrapper.prepare_data()
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-pytorch-json/gatelfpytorchjson/modelwrapperdefault.py", line 408, in prepare_data
    self.valset = self.dataset.validation_set_converted(as_batch=True)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-python-data/gatelfdata/dataset.py", line 448, in validation_set_converted
    valset = self.reshape_batch(valset, as_numpy=as_numpy)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-python-data/gatelfdata/dataset.py", line 694, in reshape_batch
    target=self.target)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-python-data/gatelfdata/dataset.py", line 626, in reshape_batch_helper
    Dataset.pad_matrix_(out_dep, tosize=seq_max_len, pad_left=pad_left, pad_value=pad_value)
  File "/data/johann/work-git/gate-lf-tests/seq-wikiner/model-pytorch-singlefeat1/FileJsonPyTorch/gate-lf-python-data/gatelfdata/dataset.py", line 516, in pad_matrix_
    tosize = max([len(x) for x in matrix])
ValueError: max() arg is an empty sequence
```

**Comment by johann-petrak** [comment]
Hmm when running from command line from within the pytorch backend repository this works but from the command line within the LF model directory it does not.

**Comment by johann-petrak** [comment]
OK, it turns out this happens because we had a failure before where the input dataset was empty. 
This in turn caused the dsindex file to contain 0 elements. 
Once the problem with the empty dataset was fixed, the old dsindex was still lingering around.
We need to find a way for how to properly remove that file, but only when the data file actually changes. 
We could check the modification dates and/or the known size of the indexed dataset (the latter could still cause a wrong index to get used for a changed dataset if the size remains absolutely the same but that would be much much less likely to happen).

**Comment by johann-petrak** [comment]
It seems this is still not working properly.

**Comment by johann-petrak** [comment]
This has now been tested and seems to work.
